{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - follow_redirects: true
          scheme: http
          timeout: 10s
          api_version: v2
          static_configs:
            - targets: []
    scrape_configs:
      - job_name: prometheus
        honor_timestamps: true
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        follow_redirects: true
        static_configs:
          - targets:
              - prometheus-{{ include "bunkerweb.fullname" . }}.{{ include "bunkerweb.namespace" . }}.svc.cluster.local:9090
      - job_name: bunkerweb
        metrics_path: /metrics
        static_configs:
          - targets:
              - {{ include "bunkerweb.fullname" . }}-metrics.{{ include "bunkerweb.namespace" . }}.svc.cluster.local:9113
{{- end }}