{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: prometheus-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "bunkerweb.selectorLabels" . | nindent 4 }}
    bunkerweb.io/component: "prometheus"
{{- end }}