{
 "title": "BunkerWeb",
 "description": "Grafana dashboard for BunkerWeb. Must be used in combination with the Prometheus exporter PRO plugin.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=\"bunkerweb\"},instance)"
    }
   },
   {
    "name": "server_name",
    "query": {
     "query": "label_values({job=\"bunkerweb\"},server_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances UP",
   "type": "stat",
   "description": "Number of BunkerWeb instances UP.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"bunkerweb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections over time (All)",
   "type": "timeseries",
   "description": "Average latency over time",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum by(state) (ceil(avg_over_time(bw_http_connections{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Instances DOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"bunkerweb\"})-sum(up{job=\"bunkerweb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(bw_http_downstream_status_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of attacks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of unique attacker IPs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (ip) (increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range]) > 0)) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error requests (4XX / 5XX)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(floor(sum(increase(bw_http_downstream_status_total{instance=~\"$instance\", server_name=~\"$server_name\", status=~\"^[45].*$\"}[$__range]))) or on() vector(0)) / clamp_min(floor(sum(increase(bw_http_downstream_status_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range]))), 1) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked attacks",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(floor(sum(increase(bw_http_downstream_status_total{instance=~\"$instance\", server_name=~\"$server_name\", status=~\"(403|444)\"}[$__range]))) or on() vector(0)) / clamp_min(floor(sum(increase(bw_http_downstream_status_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range]))), 1) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top attackers IP",
   "type": "piechart",
   "description": "Top 5 IP of attackers.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, ceil(sum by(ip) (increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top attackers  country",
   "type": "piechart",
   "description": "Top 5 countries of attackers.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, ceil(sum by(country) (increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "10 most attacked URLs",
   "type": "bargauge",
   "description": "TOP 10 of the most attacked URLs by attackers.",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, ceil(sum by(uri) (increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top attackers reason",
   "type": "piechart",
   "description": "Top 5 reasons of attackers.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, ceil(sum by(reason) (increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top attackers ASN",
   "type": "piechart",
   "description": "Top 5 ASN of attackers.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, ceil(sum by(asn) (increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 attacked Instances",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, ceil(sum by(instance) (increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 attacked server_name",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, ceil(sum by(server_name) (increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Attacks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Worldmap attack distribution",
   "type": "geomap",
   "description": "Where are attackers located around the globe.",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(country) (increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range]))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Attacks over time",
   "type": "timeseries",
   "description": "Blocked attacks over time",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__rate_interval]))",
     "legendFormat": "attacks"
    }
   ]
  },
  {
   "title": "Unique IPs over time",
   "type": "timeseries",
   "description": "Unique IPs addresses of attackers.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (ip) (increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__rate_interval]) != 0))",
     "legendFormat": "unique IP"
    }
   ]
  },
  {
   "title": "List of attacks",
   "type": "table",
   "description": "All details of each blocked attacks.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "ceil(increase(bw_http_attacks_total{instance=~\"$instance\", server_name=~\"$server_name\"}[$__range])) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Requests over time",
   "type": "timeseries",
   "description": "HTTP requests over time",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(ceil(increase(bw_http_downstream_status_total{instance=~\"$instance\",server_name=~\"$server_name\"}[$__rate_interval])))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Error requests (4XX and 5XX)",
   "type": "timeseries",
   "description": "Error requests over time (4XX and 5XX errors).",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum(ceil(increase(bw_http_downstream_status_total{instance=~\"$instance\",server_name=~\"$server_name\",status=~\"^[4-5]..$\"}[$__rate_interval])))",
     "legendFormat": "error requests"
    }
   ]
  },
  {
   "title": "Standard requests (1XX, 2XX and 3XX)",
   "type": "timeseries",
   "description": "Standard requests over time (1XX, 2XX and 3XX status).",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum(ceil(increase(bw_http_downstream_status_total{instance=~\"$instance\",server_name=~\"$server_name\",status=~\"^[1-3]..$\"}[$__rate_interval])))",
     "legendFormat": "standard requests"
    }
   ]
  },
  {
   "title": "Latency over time",
   "type": "timeseries",
   "description": "Average latency over time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(increase(bw_http_latency_sum{instance=~\"$instance\",server_name=~\"$server_name\"}[$__rate_interval]))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Bytes sent over time",
   "type": "timeseries",
   "description": "Average bytes sent over time",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(ceil(increase(bw_http_bytes_sent_sum{instance=~\"$instance\",server_name=~\"$server_name\"}[$__rate_interval])))",
     "legendFormat": "bytes sent"
    }
   ]
  },
  {
   "title": "Bytes received over time",
   "type": "timeseries",
   "description": "Average bytes received over time",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(ceil(increase(bw_http_bytes_received_sum{instance=~\"$instance\", server_name=~\"$server_name\"}[$__rate_interval])))",
     "legendFormat": "bytes received"
    }
   ]
  }
 ]
}